import React, { useRef } from "react";
import { useReactToPrint } from "react-to-print";

const ExportTasksPreview = ({ tasks, currentUser  }) => {
  const printRef = useRef();

  const handlePrint = useReactToPrint({
    content: () => printRef.current,
    documentTitle: "AssignedTasksReport",
  });

  return (
    <div className="flex flex-col items-center space-y-4">
     { currentUser !== "HR" && (
      <button
        onClick={handlePrint}
        className="px-5 py-2 bg-blue-600 text-white rounded-lg shadow-lg hover:bg-blue-500 transition font-medium flex items-center gap-2"
      >
        🖨️ Print
      </button>
     )
       
     }

      <div className="hidden">
        <div ref={printRef} className="p-6 bg-white text-gray-800">
          <div className="flex flex-col items-center mb-6">
            <img src="/logo.png" alt="Logo" className="w-16 h-16 mb-2" />
            <h1 className="text-2xl font-bold">Assigned Tasks Report</h1>
            <p className="text-sm text-gray-600">
              Generated on: {new Date().toLocaleDateString()}
            </p>
          </div>

          <table className="w-full border-collapse border border-gray-300 text-sm shadow-sm">
            <thead className="bg-gray-200 text-gray-700">
              <tr>
                <th className="border border-gray-300 px-4 py-2 text-left">Name</th>
                <th className="border border-gray-300 px-4 py-2 text-left">Position</th>
                <th className="border border-gray-300 px-4 py-2 text-left">Status</th>
                <th className="border border-gray-300 px-4 py-2 text-left">Date Assigned</th>
              </tr>
            </thead>
            <tbody>
              {tasks.map((task, idx) => (
                <tr key={idx} className={idx % 2 === 0 ? "bg-white" : "bg-gray-50"}>
                  <td className="border border-gray-300 px-4 py-2">
                    {task.assign?.firstName} {task.assign?.lastName}
                  </td>
                  <td className="border border-gray-300 px-4 py-2">
                    {task.assign?.role || "N/A"}
                  </td>
                  <td className="border border-gray-300 px-4 py-2">{task.status}</td>
                  <td className="border border-gray-300 px-4 py-2">
                    {task.createdAt
                      ? new Date(task.createdAt).toLocaleDateString()
                      : "N/A"}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>

          <div className="mt-6 text-sm text-gray-500 text-right">
            Report generated by SFCG TASK Management System
          </div>
        </div>
      </div>
    </div>
  );
};

export default ExportTasksPreview;
